CREATE TABLE Continents (id INTEGER PRIMARY KEY, name TEXT);
INSERT INTO Continents VALUES(1,'North America');
INSERT INTO Continents VALUES(2,'Caribbean');
INSERT INTO Continents VALUES(3,'Central America');
CREATE TABLE Countries (id INTEGER PRIMARY KEY, name TEXT, continentId NUMERIC);
INSERT INTO Countries VALUES(1,'Bermuda',1);
INSERT INTO Countries VALUES(2,'Canada',1);
INSERT INTO Countries VALUES(3,'Greenland',1);
INSERT INTO Countries VALUES(4,'Mexico',1);
INSERT INTO Countries VALUES(5,'Saint Pierre and Miquelon',1);
INSERT INTO Countries VALUES(6,'United States',1);
INSERT INTO Countries VALUES(7,'Anguilla',2);
INSERT INTO Countries VALUES(8,'Antigua and Barbuda',2);
INSERT INTO Countries VALUES(9,'Aruba',2);
INSERT INTO Countries VALUES(10,'Bahamas',2);
INSERT INTO Countries VALUES(11,'Barbados',2);
INSERT INTO Countries VALUES(12,'Bonaire',2);
INSERT INTO Countries VALUES(13,'British Virgin Islands',2);
INSERT INTO Countries VALUES(14,'Cayman Islands',2);
INSERT INTO Countries VALUES(15,'Clipperton Island ',2);
INSERT INTO Countries VALUES(16,'Cuba',2);
INSERT INTO Countries VALUES(17,'Curaçao',2);
INSERT INTO Countries VALUES(18,'Dominica',2);
INSERT INTO Countries VALUES(19,'Guadeloupe',2);
INSERT INTO Countries VALUES(20,'Haiti',2);
INSERT INTO Countries VALUES(21,'Jamaica',2);
INSERT INTO Countries VALUES(22,'Martinique',2);
INSERT INTO Countries VALUES(23,'Montserrat',2);
INSERT INTO Countries VALUES(24,'Navassa Island',2);
INSERT INTO Countries VALUES(25,'Puerto Rico',2);
INSERT INTO Countries VALUES(26,'Saba',2);
INSERT INTO Countries VALUES(27,'Saint Barthélemy',2);
INSERT INTO Countries VALUES(28,'Saint Kitts and Nevis',2);
INSERT INTO Countries VALUES(29,'Saint Lucia',2);
INSERT INTO Countries VALUES(30,'Saint Martin',2);
INSERT INTO Countries VALUES(31,'Saint Vincent and the Grenadines',2);
INSERT INTO Countries VALUES(32,'Sint Eustatius',2);
INSERT INTO Countries VALUES(33,'Sint Maarten',2);
INSERT INTO Countries VALUES(34,'Trinidad and Tobago',2);
INSERT INTO Countries VALUES(35,'Turks and Caicos Islands',2);
INSERT INTO Countries VALUES(36,'United States Virgin Islands',2);
INSERT INTO Countries VALUES(37,'Belize',3);
INSERT INTO Countries VALUES(38,'Costa Rica',3);
INSERT INTO Countries VALUES(39,'El Salvador',3);
INSERT INTO Countries VALUES(40,'Guatemala',3);
INSERT INTO Countries VALUES(41,'Honduras',3);
INSERT INTO Countries VALUES(42,'Nicaragua',3);
INSERT INTO Countries VALUES(43,'Panama',3);
CREATE TABLE Regions (id INTEGER PRIMARY KEY, name TEXT, countryId NUMERIC, surface NUMERIC, points TEXT);
